[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 10

[[main]]
  name = "About"
  url = "/about/"
  weight = 20

[[legal]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 10

[[legal]]
  name = "Colophon"
  url = "/colophon/"
  weight = 20

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/henkverlinde/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/henkverlinde"
  weight = 30
