baseurl = "/"
languageCode = "en-US"
languageLang = "en"
title = "Henk Verlinde"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

disableHugoGeneratorInject = true
enableRobotsTXT = true
enableEmoji = true

pygmentsUseClasses = true
pygmentsCodeFences = true

paginate = 2

[permalinks]
  blog = "/:title/"

[menu]
  [[menu.main]]
    name = "Profile"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Writing"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 3
  [[menu.social]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/henkverlinde/"
    weight = 1
  [[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/henkverlinde"
    weight = 2

[params]
  footer = "I enjoy designing and building things that look nice and work well, whether it’s websites, services or brands. I’ve been fortunate enough to have that be my day job, at the digital agency <a href=\"#\">Divide & Conquer</a> located in Vasastan, Stockholm."
